### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Ivshti** [fulmicoton/tantivy-wasm#1]
This repo currently fails to compile with latest tantivy cause of API differences. I tried reverting the repo to a commit from Aug 21 2018 but then the problem is the downcast crate does not compile (any is ambiguous cause it’s in the std but also defined by it)

Any solutions?

**Comment by fulmicoton** [comment]
sorry no support on this :)

I'm way too busy with tantivy. If you have a super interesting use case please share it on the chat, and we might reprioritize WASM.
